"""add llm config to company

Revision ID: 234127a72279
Revises: 9dc50959faec
Create Date: 2026-02-16 17:38:35.897011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234127a72279'
down_revision: Union[str, Sequence[str], None] = '9dc50959faec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('llm_provider', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('openai_api_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'openai_api_key')
    op.drop_column('companies', 'llm_provider')
    # ### end Alembic commands ###
