"""add memory summary

Revision ID: 903d105e8fff
Revises: a266e869a52a
Create Date: 2026-02-21 14:42:55.621595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903d105e8fff'
down_revision: Union[str, Sequence[str], None] = 'a266e869a52a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('memory_summary', sa.Text(), nullable=True))
    op.drop_constraint('chat_sessions_user_id_fkey', 'chat_sessions', type_='foreignkey')
    op.drop_constraint('chat_sessions_company_id_fkey', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'chat_sessions', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('chat_sessions_company_id_fkey', 'chat_sessions', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('chat_sessions_user_id_fkey', 'chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_sessions', 'memory_summary')
    # ### end Alembic commands ###
